version: 0.2

env:
  # Replace with your actual AWS region
  AWS_REGION: "eu-west-2"
  ECR_REPOSITORY_URI: "637423277250.dkr.ecr.eu-west-2.amazonaws.com/my-restapp-image"
  

artifacts:
  # Optional: Specify artifacts to upload to S3 bucket after build (e.g., logs)
  files:
    - build.log

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - mvn clean install # Replace with your specific Maven commands (consider skipping tests for faster builds)

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t restapp:latest . # Use environment variable for image name

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - |
        AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - echo "ECR Repo URL: $ECR_REPOSITORY_URI"
      - |
        IMAGE_URI=$(docker push $ECR_REPOSITORY_URI:latest)
        echo "Image pushed successfully: $IMAGE_URI"
