version: 0.2

artifacts:
  # Optional: Specify artifacts to upload to S3 bucket after build (e.g., logs)
  files:
    - build.log

phases:

  install:
     commands:
      - echo "Installing dependencies..."
      - cd microservices/restapp
      - pwd
      - echo "changed the Directory"
      - mvn clean install # Replace with your specific Maven commands (consider skipping tests for faster builds)
      
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t restapp:latest . # Use environment variable for image name

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - echo "ECR Repo URL: $ECR_REPOSITORY_URI"
      - docker build -t $ECR_REPOSITORY_URI:latest .
      - docker push $ECR_REPOSITORY_URI:latest
      - IMAGE_URI=$ECR_REPOSITORY_URI:latest
      - echo "Image pushed successfully: $IMAGE_URI"
